# ~/.bash_logout: executed by bash(1) when login shell exits.

# when leaving the console clear the screen to increase privacy

if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi
#-----------------------------------------
cd /home/dev/Desktop/CS1XC3     #Bash script to automatically push all changes
git add .                       #when we exit shell using logout 
git commit -m "Shell Logout commit."
git push
#------------------------------------------
